{% set version = "0.28.0" %}

package:
  name: incognita
  version: {{ version }}

source:
  url: https://github.com/the-scouts/incognita/releases/download/v{{ version }}/incognita-{{ version }}.tar.gz
  sha256: fdff6d46108ff630449336e4d3134f883a687cdc426383bca202284c1eb04ed2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - pandas
    - numpy
    - folium
    - branca
    - geopandas >=0.8
    - shapely
    - pyarrow
    - pygeos

test:
  imports:
    - incognita

about:
  home: https://github.com/the-scouts/incognita
  license: MIT
  license_file: LICENSE
  summary: Mapping the annual UK Scout Census to local geographies
  dev_url: https://github.com/the-scouts/incognita

extra:
  recipe-maintainers:
    - AA-Turner
